# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kaldi
quarkus.datasource.password=kaldi123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kaldi_db

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Disable Dev Services
quarkus.devservices.enabled=false

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Port
quarkus.http.port=8080

# JWT
mp.jwt.verify.issuer=kaldi-api
mp.jwt.verify.publickey.location=publicKey.pem

# OpenAPI JWT security scheme
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=jwt
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer
